language: python
cache: pip

python:
 - pypy
 - pypy-3.8
 - 3.6
 - 2.7
 - 3.5
 - 3.4

sudo: false

install:
 - pip install -U pip
 - pip install -U flake8

script:
 # Pretend tests
 - flake8 --statistics --count .

matrix:
  fast_finish: true
